robot1:
  namespace: ''
  grasp_action_topic: 'franka_gripper/grasp'
  homing_action_topic: 'franka_gripper/homing'
  gripper_command_topic: 'gripper_client/target_gripper_width_percent'
  joint_states_topic: 'franka_gripper/joint_states' 
  gripper_epsilon_inner: '0.08' 
  gripper_epsilon_outer: '0.08' 
  gripper_speed: '1.0' 
  gripper_force: '70.0' 